name: act
description: act

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.10.7

environment:
  sdk: '>=2.12.0 <3.0.0'

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0 # Add this line

  provider: ^6.0.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  mvc_pattern: ^8.8.0+03
  global_configuration: ^2.0.0-nullsafety.1
  http: ^0.13.4
  fluttertoast: ^8.0.9
  intl_utils: ^2.6.1
  email_validator: ^2.0.1
  flutter_html: ^2.1.1
  url_launcher: ^6.0.20
  pull_to_refresh: ^2.0.0
  image_picker: ^0.8.4+10
  image_cropper: ^1.4.1
  dio: ^4.0.4
  dropdown_formfield:
    git:
      url: https://github.com/samiraj99/dropdown_formfield.git
      ref: master
  flutter_holo_date_picker: ^1.0.0-nullsafety.4
  international_phone_input:
    git:
      url: https://github.com/n-ice-ch/flutter_international_phone_input.git
      ref: main
  intl_phone_number_input: ^0.7.0+2
  flutter_slidable: ^0.6.0
  cached_network_image: ^3.2.0
  flutter_datetime_picker: ^1.5.1
  table_calendar: ^3.0.4
  shared_preferences: ^2.0.13
  carousel_slider: ^4.0.0
  flutter_osm_plugin: 0.31.0
  geocoding: ^2.0.2
  map_launcher: ^2.1.1+1
  flutter_svg:
  upgrader: ^3.13.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/
    - assets/html/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true